### PR TITLE
Integrated Mongodb

### PR DESCRIPTION
**Pull request by VanshVg**
I have integrated Mongodb in server side but I haven't added mongodb url so please add mongodb url in data.js.

### CODE REVIEW

**Review by samuel-ma — COMMENTED** [review]
First confirm if it's working on your side
And send me a screenshot as well

**Review by samuel-ma — COMMENTED** [review]
I have one cluster on Atlas right now, so before clearing the data 
I want u to confirm whether this code is working fine before I merge the changes

**Comment by VanshVg** [comment]
Here is the image
image

You have to replace your cluster url in mongodb_url variable in data.js file and it'll work perfectly.

**Review by samuel-ma — APPROVED** [review]
Great work @VanshVg 
I'll merge these changes into the main branch
Plz, take a look at the list of issues as well if u don't mind
I could use another hand working on this project

**Comment by VanshVg** [comment]
Ok sure !

**Comment by VanshVg** [comment]
Hey @samuel-ma can I know why haven't you merged yet?

**Comment by samuel-ma** [comment]
> Hey @samuel-ma can I know why haven't you merged yet?

Sorry @VanshVg, I didn't see this reply
I've been busy with another project and never got to working on this one
I'll merge ur changes immediately tho
Thanks for the help....

**Comment by VanshVg** [comment]
Yeah no problem.
Good Luck for another project.

**Pull request merged**
